config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :interview

  get 'testing', to: 'testing#index'
  post 'save_test', to: 'testing#save_test'

  get 'result', to: 'testing#result'

  post 'start', to: 'interview#start'

  namespace :admin do
    resources :interview
    get '/', to: 'admin#index'
  end

  root to: 'interview#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  has_many :results
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :interviews
end

app/models/interview.rb
class Interview < ApplicationRecord
  has_many :questions, inverse_of: :interview
  has_many :sessions
  belongs_to :category

  accepts_nested_attributes_for :questions

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :interview, inverse_of: :questions
  has_many :answers
  has_many :results

  accepts_nested_attributes_for :interview

end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :session
  belongs_to :question
  belongs_to :answer
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :interview
  has_many :results
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout 'admin'

  before_action :authenticate_user!

  def index
  end
end

app/controllers/admin/interview_controller.rb
class Admin::InterviewController < Admin::AdminController
  before_action :set_interview, only: [:show]

  def index
    @interviews = Interview.all

    respond_to do |format|
      format.html
      format.json { render json: @interviews }
    end
  end

  def new
    @interview = Interview.new
    @question = @interview.questions.build
    categories = Category.all

    respond_to do |format|
      format.html
      format.json { render json: categories }
    end
  end

  def create

    @interview = Interview.new(interview_params)
    @interview.save

    @interview.questions.build

    redirect_to admin_interview_index_path

  end

  def show
    @interview_id = set_interview.id

    questions = @interview.questions
    sessions = @interview.sessions
    # answers = [{ :question => [:answers => []] }]
    answers = []

    @interview.questions.each do |q|
      answer_count = 0
      q.answers.each do |a|
        answer_count = answer_count + a.content.to_i
      end
      answers << {"question" => q.name, "answer" => answer_count}
    end

    @interview = ["questions" => questions, "answers" => answers]

    respond_to do |format|
      format.html
      format.json { render json: @interview }
    end

  end

  private

  def set_interview
    @interview = Interview.find(params[:id]);
  end

  def interview_params
    params.require(:interview).permit(:name, :description, :category_id, questions_attributes: [:name])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/interview_controller.rb
class InterviewController < ApplicationController

  def index
    @interviews = Interview.all
    @session = Session.new
    categories = Category.all

    interviews = [@interviews, categories]

    respond_to do |format|
      format.html
      format.json { render json: interviews}
    end
  end


  def start
    session_test = Session.new(test_params)
    session_test.save

    session[:testing_id] = session_test.id

    redirect_to testing_path

  end


  def show

  end


  private

  def test_params
    params.permit(:interview_id)
  end

end

app/controllers/testing_controller.rb
class TestingController < ApplicationController
  def index
    test = session[:testing_id]
    session_test = Session.find(test)
    interview_test = Interview.find(session_test.interview_id)
    @questions = interview_test.questions

    respond_to do |format|
      if @questions
        format.html
        format.json { render json: @questions }
      else
        format.json { render json: @questions.erros.full_messsages, status: :unprocessable_entity }
      end
    end
  end

  def save_test
    #  FIXME It's so ugly =(
    data = testing_params[:data]
    data.each do |d|
      answers = Answer.new(d)
      answers.save
      result = Result.new
      result.session_id = session[:testing_id]
      result.question_id = d[:question_id]
      result.answer_id = answers.id
      result.save
    end

    redirect_to action: 'result'
  end

  def result
    #  сколько человек прошли опрос
    # какой процент из них доволен тем-то и тем-то
    # сколько человек ответило по каждлому баллу
    @results = []
    testing = Session.find(session[:testing_id])
    testing.results.each do |r|
      result = {question: r.question.name, answer: r.answer.content}
      @results << result
    end
    
    respond_to do |format|
      if @results
        format.html
        format.json { render json: @results }
      else
        format.json { render json: @results.erros.full_messsages, status: :unprocessable_entity }
      end
    end

  end

  def testing_params
    params.permit(data: [:question_id, :content])
  end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interview_helper.rb
module InterviewHelper
end

app/helpers/testing_helper.rb
module TestingHelper
end

app/views/admin/admin/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      Привет, Admin!
    </div>
  </div>
</div>

app/views/admin/interview/index.html.erb
<div class="container">
  <% @interviews.each do |i| %>
      <div class="row">
        <div class="col">
          <div class="jumbotron">
            <h1 class="display-3"><%= i.name %></h1>
            <p class="lead"><%= i.description %></p>
            <hr class="my-4">
            <p class="lead">
              <a class="btn btn-success btn-lg" href="#" role="button">Изменить</a>

              <%= link_to "Посмотреть статистику", admin_interview_path(i), :class => "btn btn-info btn-lg" %>

            </p>
            <h2 class="badge badge-info"><%= i.category.name %></h2>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/admin/interview/new.html.erb
<div class="container">
  <h3 class="display-4 text-center heading">Новый опрос</h3>
  <hr>

  <%= form_for @interview, url: {action: "create"} do |f| %>
      <div id="app" class="vue_app">

        <div class="row">
          <div class="col-md-8 push-md-2 builder_interview">
            <div class="form-group">
              <label for="title" class="col-form-label">Название опроса</label>
              <input class="form-control" type="text" name="interview[name]" placeholder="Название" id="example-text-input">
            </div>
            <div class="form-group">
              <label for="title" class="col-form-label">Краткое описание</label>
              <input class="form-control" type="text" name="interview[description]" placeholder="Описание" id="example-text-input">
            </div>
            <hr>
            <div v-for="q in questions">
              <%= f.fields_for :questions, :index => @question.id do |q| %>
                  <div class="form-group">
                    <label for="exampleTextarea">Вопрос
                      <span class="badge badge-info question_number">{{ q.number }}</span></label>
                    <textarea class="form-control" id="exampleTextarea" rows="3" v-bind:name="q.dinName"></textarea>
                  </div>
              <% end %>
            </div>
            <div class="row">
              <div class="form-group col">
                <button type="button" class="btn btn-info" @click.prevent="add()">Добавить вопрос</button>
              </div>

              <div class="form-group col">
                <div class="form-group">

                  <select v-model="category" class="form-control" name="interview[category_id]">
                    <option v-for="option in options" v-bind:value="option.value">
                      {{ option.text }}
                    </option>
                  </select>
                </div>
              </div>
              <div class="form-group col">
                <input type="submit" class="btn btn-success float-right" value="Готово">
              </div>
            </div>

          </div>
        </div>
      </div>
  <% end %>

</div>

<%= javascript_include_tag 'https://unpkg.com/vue' %>

app/views/admin/interview/show.html.erb
<div class="statistics" id="<%= @interview_id %>">
  <div class="container">
    <div class="row">
      <div class="col">
        <h1>SHOW</h1>

        <ul>
          <li>Получить вопросы опроса</li>
          <li>Получить людей, прошедших опрос</li>
          <li>Получить количество баллов по каждому вопросу</li>
        </ul>
      </div>

      <canvas id="myChart"></canvas>
      </div>
    </div>
  </div>


<%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.bundle.min.js' %>

app/views/interview/index.html.erb
<div id="interview">
  <div class="container">
    <div class="row justify-content-center my-3">
      <div class="col-md-5">
        <div class="btn-group" role="group" aria-label="Basic example">
          <button type="button" class="btn btn-secondary" @click.prevent="medical()">Здравоохранение</button>
          <button type="button" class="btn btn-secondary" @click.prevent="culture()">Культура</button>
          <button type="button" class="btn btn-secondary" @click.prevent="education()">Образование</button>
          <button type="button" class="btn btn-secondary" @click.prevent="all()">Все</button>
        </div>
      </div>
    </div>

        <div class="row">
          <div class="col">
            <div class="jumbotron" v-for="i in interviews">
              <h1 class="display-3">{{ i.name }}</h1>
              <p class="lead">{{ i.description }}</p>
              <hr class="my-4">
              <p class="lead">
                <%= form_tag(action: "start") do %>
                    <input type="hidden" name="interview_id" id="interview_id" v-model="i.id">
                    <%= submit_tag 'Пройти опрос', :class => "btn btn-success btn-lg" %>
                <% end %>
              </p>
              <!--FIXME insert category name-->
              <h2 class="badge badge-info"><%#= i.category.name %></h2>
            </div>
          </div>
        </div>

  </div>
</div>





<%= javascript_include_tag 'https://unpkg.com/vue' %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
    </div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gmu</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

</head>

<body>
<header class="mb-3">
  <%= render 'layouts/messages' %>
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">ADMIN</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        </li><li class="nav-item">
        <%= link_to "Опросы", admin_interview_index_path, class: "nav-link"%>
      </li>
        <li class="nav-item">
          <%= link_to "Создать опрос", new_admin_interview_path, class: "nav-link"%>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <% if user_signed_in? %>
            <%= link_to "Выйти", destroy_user_session_path, method: :delete, class: "btn btn-outline-success my-2 my-sm-0" %>
        <% else %>
            <%= link_to "Войти", new_user_session_path, class: "btn btn-outline-success my-2 my-sm-0" %>
        <% end %>
      </form>
    </div>
  </nav>
</header>


<%= yield %>

<%= javascript_include_tag 'https://unpkg.com/axios/dist/axios.min.js' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gmu</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>


</head>

<body>
<header class="mb-3">
  <%= render 'layouts/messages' %>
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">GMU</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Главная", root_path, class: "nav-link"%>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <% if user_signed_in? %>
            <%= link_to "Выйти", destroy_user_session_path, method: :delete, class: "btn btn-outline-success my-2 my-sm-0" %>
        <% else %>
            <%= link_to "Войти", new_user_session_path, class: "btn btn-outline-success my-2 my-sm-0" %>
        <% end %>
      </form>
    </div>
  </nav>
</header>


<%= yield %>



<%= javascript_include_tag 'https://unpkg.com/axios/dist/axios.min.js' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>
</html>

app/views/testing/index.html.erb
<div id="test">
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="jumbotron">
          <p class="lead">{{ question.name }}</p>
          <hr class="my-4">
          <p class="lead">Оцените по шкале</p>
          <p class="lead">
            <nav aria-label="">

              <ul class="pagination pagination-lg">
                <label class="btn btn-info btn-lg page-item m-0 mr-1">
                  <input class="" type="radio" v-model="question.answer_number" value="1"/> 1
                </label>
                <label class="btn btn-info btn-lg page-item m-0 mr-1">
                  <input class="" type="radio" v-model="question.answer_number" value="2"/> 2
                </label>
                <label class="btn btn-info btn-lg page-item m-0 mr-1">
                  <input class="" type="radio" v-model="question.answer_number" value="3"/> 3
                </label>
                <label class="btn btn-info btn-lg page-item m-0 mr-1">
                  <input class="" type="radio" v-model="question.answer_number" value="4"/> 4
                </label>
                <label class="btn btn-info btn-lg page-item m-0 mr-1">
                  <input class="" type="radio" v-model="question.answer_number" value="5"/> 5
                </label>
                <label class="btn btn-info btn-lg page-item m-0 mr-1">
                  <input class="" type="radio" v-model="question.answer_number" value="6"/> 6
                </label>
                <label class="btn btn-info btn-lg page-item m-0 mr-1">
                  <input class="" type="radio" v-model="question.answer_number" value="7"/> 7
                </label>
                <label class="btn btn-info btn-lg page-item m-0 mr-1">
                  <input class="" type="radio" v-model="question.answer_number" value="8"/> 8
                </label>
                <label class="btn btn-info btn-lg page-item m-0 mr-1">
                  <input class="" type="radio" v-model="question.answer_number" value="9"/> 9
                </label>
                <label class="btn btn-info btn-lg page-item m-0 mr-1">
                  <input class="" type="radio" v-model="question.answer_number" value="10"/> 10
                </label>

                </li>
              </ul>
            </nav>

            <button class="btn btn-info" @click.prevent="nextQuestion()">Далее</button>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag 'https://unpkg.com/vue' %>

app/views/testing/result.html.erb
<div id="result">
  <h1>RESULT</h1>
  <ul>
    <% @results.each do |r| %>
        <li><%= r[:question] %> - Ответ: <%= r[:answer]%></li>
    <% end %>
  </ul>


  <div class="chart-container">
    <canvas id="chart"></canvas>
  </div>

</div>


<%= javascript_include_tag 'https://unpkg.com/vue' %>
<%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.bundle.min.js' %>